/*
 * generated by Xtext
 */
package com.sandy.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JoveNotesUiModule extends com.sandy.xtext.ui.AbstractJoveNotesUiModule {
	public JoveNotesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
