/*
 * generated by Xtext
 */
package com.sandy.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.sandy.xtext.ui.internal.JoveNotesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JoveNotesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JoveNotesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JoveNotesActivator.getInstance().getInjector(JoveNotesActivator.COM_SANDY_XTEXT_JOVENOTES);
	}
	
}
