/*
 * generated by Xtext
 */
package com.sandy.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.sandy.xtext.services.JoveNotesGrammarAccess;

public class JoveNotesParser extends AbstractContentAssistParser {
	
	@Inject
	private JoveNotesGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.sandy.xtext.ui.contentassist.antlr.internal.InternalJoveNotesParser createParser() {
		com.sandy.xtext.ui.contentassist.antlr.internal.InternalJoveNotesParser result = new com.sandy.xtext.ui.contentassist.antlr.internal.InternalJoveNotesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNotesElementAccess().getAlternatives(), "rule__NotesElement__Alternatives");
					put(grammarAccess.getJoveNotesAccess().getGroup(), "rule__JoveNotes__Group__0");
					put(grammarAccess.getChapterDetailsAccess().getGroup(), "rule__ChapterDetails__Group__0");
					put(grammarAccess.getWordMeaningAccess().getGroup(), "rule__WordMeaning__Group__0");
					put(grammarAccess.getQuestionAnswerAccess().getGroup(), "rule__QuestionAnswer__Group__0");
					put(grammarAccess.getFIBAccess().getGroup(), "rule__FIB__Group__0");
					put(grammarAccess.getDefinitionAccess().getGroup(), "rule__Definition__Group__0");
					put(grammarAccess.getCharacterAccess().getGroup(), "rule__Character__Group__0");
					put(grammarAccess.getTeacherNoteAccess().getGroup(), "rule__TeacherNote__Group__0");
					put(grammarAccess.getMatchingAccess().getGroup(), "rule__Matching__Group__0");
					put(grammarAccess.getMatchPairAccess().getGroup(), "rule__MatchPair__Group__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getTrueFalseAccess().getGroup(), "rule__TrueFalse__Group__0");
					put(grammarAccess.getChemEquationAccess().getGroup(), "rule__ChemEquation__Group__0");
					put(grammarAccess.getChemCompoundAccess().getGroup(), "rule__ChemCompound__Group__0");
					put(grammarAccess.getSpellbeeAccess().getGroup(), "rule__Spellbee__Group__0");
					put(grammarAccess.getImageLabelAccess().getGroup(), "rule__ImageLabel__Group__0");
					put(grammarAccess.getImageLabelAccess().getGroup_6(), "rule__ImageLabel__Group_6__0");
					put(grammarAccess.getHotSpotAccess().getGroup(), "rule__HotSpot__Group__0");
					put(grammarAccess.getEquationAccess().getGroup(), "rule__Equation__Group__0");
					put(grammarAccess.getEquationAccess().getGroup_6(), "rule__Equation__Group_6__0");
					put(grammarAccess.getEqSymbolAccess().getGroup(), "rule__EqSymbol__Group__0");
					put(grammarAccess.getRefToContextAccess().getGroup(), "rule__RefToContext__Group__0");
					put(grammarAccess.getCMapAccess().getGroup(), "rule__CMap__Group__0");
					put(grammarAccess.getJoveNotesAccess().getProcessingHintsAssignment_0(), "rule__JoveNotes__ProcessingHintsAssignment_0");
					put(grammarAccess.getJoveNotesAccess().getChapterDetailsAssignment_1(), "rule__JoveNotes__ChapterDetailsAssignment_1");
					put(grammarAccess.getJoveNotesAccess().getNotesElementsAssignment_2(), "rule__JoveNotes__NotesElementsAssignment_2");
					put(grammarAccess.getProcessingHintsAccess().getSkipGenerationAssignment(), "rule__ProcessingHints__SkipGenerationAssignment");
					put(grammarAccess.getChapterDetailsAccess().getTestPaperAssignment_0(), "rule__ChapterDetails__TestPaperAssignment_0");
					put(grammarAccess.getChapterDetailsAccess().getSubjectNameAssignment_2(), "rule__ChapterDetails__SubjectNameAssignment_2");
					put(grammarAccess.getChapterDetailsAccess().getChapterNumberAssignment_4(), "rule__ChapterDetails__ChapterNumberAssignment_4");
					put(grammarAccess.getChapterDetailsAccess().getSubChapterNumberAssignment_6(), "rule__ChapterDetails__SubChapterNumberAssignment_6");
					put(grammarAccess.getChapterDetailsAccess().getChapterNameAssignment_8(), "rule__ChapterDetails__ChapterNameAssignment_8");
					put(grammarAccess.getWordMeaningAccess().getWordAssignment_1(), "rule__WordMeaning__WordAssignment_1");
					put(grammarAccess.getWordMeaningAccess().getMeaningAssignment_2(), "rule__WordMeaning__MeaningAssignment_2");
					put(grammarAccess.getQuestionAnswerAccess().getQuestionAssignment_1(), "rule__QuestionAnswer__QuestionAssignment_1");
					put(grammarAccess.getQuestionAnswerAccess().getAnswerAssignment_2(), "rule__QuestionAnswer__AnswerAssignment_2");
					put(grammarAccess.getQuestionAnswerAccess().getCmapAssignment_3(), "rule__QuestionAnswer__CmapAssignment_3");
					put(grammarAccess.getFIBAccess().getQuestionAssignment_1(), "rule__FIB__QuestionAssignment_1");
					put(grammarAccess.getFIBAccess().getAnswersAssignment_2(), "rule__FIB__AnswersAssignment_2");
					put(grammarAccess.getDefinitionAccess().getTermAssignment_1(), "rule__Definition__TermAssignment_1");
					put(grammarAccess.getDefinitionAccess().getDefinitionAssignment_2(), "rule__Definition__DefinitionAssignment_2");
					put(grammarAccess.getDefinitionAccess().getCmapAssignment_3(), "rule__Definition__CmapAssignment_3");
					put(grammarAccess.getCharacterAccess().getCharacterAssignment_1(), "rule__Character__CharacterAssignment_1");
					put(grammarAccess.getCharacterAccess().getEstimateAssignment_2(), "rule__Character__EstimateAssignment_2");
					put(grammarAccess.getCharacterAccess().getCmapAssignment_3(), "rule__Character__CmapAssignment_3");
					put(grammarAccess.getTeacherNoteAccess().getNoteAssignment_1(), "rule__TeacherNote__NoteAssignment_1");
					put(grammarAccess.getTeacherNoteAccess().getCmapAssignment_2(), "rule__TeacherNote__CmapAssignment_2");
					put(grammarAccess.getMatchingAccess().getSkipReverseQuestionAssignment_1(), "rule__Matching__SkipReverseQuestionAssignment_1");
					put(grammarAccess.getMatchingAccess().getQuestionAssignment_2(), "rule__Matching__QuestionAssignment_2");
					put(grammarAccess.getMatchingAccess().getPairsAssignment_4(), "rule__Matching__PairsAssignment_4");
					put(grammarAccess.getMatchPairAccess().getMatchQuestionAssignment_0(), "rule__MatchPair__MatchQuestionAssignment_0");
					put(grammarAccess.getMatchPairAccess().getMatchAnswerAssignment_2(), "rule__MatchPair__MatchAnswerAssignment_2");
					put(grammarAccess.getEventAccess().getEventAssignment_1(), "rule__Event__EventAssignment_1");
					put(grammarAccess.getEventAccess().getTimeAssignment_2(), "rule__Event__TimeAssignment_2");
					put(grammarAccess.getTrueFalseAccess().getStatementAssignment_1(), "rule__TrueFalse__StatementAssignment_1");
					put(grammarAccess.getTrueFalseAccess().getTruthValueAssignment_2(), "rule__TrueFalse__TruthValueAssignment_2");
					put(grammarAccess.getTrueFalseAccess().getJustificationAssignment_3(), "rule__TrueFalse__JustificationAssignment_3");
					put(grammarAccess.getChemEquationAccess().getEquationAssignment_1(), "rule__ChemEquation__EquationAssignment_1");
					put(grammarAccess.getChemEquationAccess().getDescriptionAssignment_2(), "rule__ChemEquation__DescriptionAssignment_2");
					put(grammarAccess.getChemEquationAccess().getNotesAssignment_3(), "rule__ChemEquation__NotesAssignment_3");
					put(grammarAccess.getChemCompoundAccess().getSymbolAssignment_1(), "rule__ChemCompound__SymbolAssignment_1");
					put(grammarAccess.getChemCompoundAccess().getChemicalNameAssignment_2(), "rule__ChemCompound__ChemicalNameAssignment_2");
					put(grammarAccess.getChemCompoundAccess().getCommonNameAssignment_3(), "rule__ChemCompound__CommonNameAssignment_3");
					put(grammarAccess.getSpellbeeAccess().getWordAssignment_1(), "rule__Spellbee__WordAssignment_1");
					put(grammarAccess.getImageLabelAccess().getCaptionAssignment_1(), "rule__ImageLabel__CaptionAssignment_1");
					put(grammarAccess.getImageLabelAccess().getImageNameAssignment_4(), "rule__ImageLabel__ImageNameAssignment_4");
					put(grammarAccess.getImageLabelAccess().getHotspotsAssignment_5(), "rule__ImageLabel__HotspotsAssignment_5");
					put(grammarAccess.getImageLabelAccess().getHotspotsAssignment_6_1(), "rule__ImageLabel__HotspotsAssignment_6_1");
					put(grammarAccess.getHotSpotAccess().getXAssignment_0(), "rule__HotSpot__XAssignment_0");
					put(grammarAccess.getHotSpotAccess().getYAssignment_2(), "rule__HotSpot__YAssignment_2");
					put(grammarAccess.getHotSpotAccess().getLabelAssignment_4(), "rule__HotSpot__LabelAssignment_4");
					put(grammarAccess.getEquationAccess().getEquationAssignment_1(), "rule__Equation__EquationAssignment_1");
					put(grammarAccess.getEquationAccess().getDescriptionAssignment_3(), "rule__Equation__DescriptionAssignment_3");
					put(grammarAccess.getEquationAccess().getSymbolsAssignment_5(), "rule__Equation__SymbolsAssignment_5");
					put(grammarAccess.getEquationAccess().getSymbolsAssignment_6_1(), "rule__Equation__SymbolsAssignment_6_1");
					put(grammarAccess.getEqSymbolAccess().getSymbolAssignment_0(), "rule__EqSymbol__SymbolAssignment_0");
					put(grammarAccess.getEqSymbolAccess().getDescriptionAssignment_2(), "rule__EqSymbol__DescriptionAssignment_2");
					put(grammarAccess.getRefToContextAccess().getContextAssignment_3(), "rule__RefToContext__ContextAssignment_3");
					put(grammarAccess.getRefToContextAccess().getQuestionsAssignment_4(), "rule__RefToContext__QuestionsAssignment_4");
					put(grammarAccess.getCMapAccess().getContentAssignment_2(), "rule__CMap__ContentAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.sandy.xtext.ui.contentassist.antlr.internal.InternalJoveNotesParser typedParser = (com.sandy.xtext.ui.contentassist.antlr.internal.InternalJoveNotesParser) parser;
			typedParser.entryRuleJoveNotes();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public JoveNotesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JoveNotesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
